# .goreleaser.yml

before:
  hooks:
  - ./set-version.sh

builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    goarm:
      - 7
    ignore:
      - goarch: 386
        goos: darwin
archives:
  - format_overrides:
      - goos: windows
        format: zip
