# .goreleaser.yml

before:
  hooks:
  - ./set-version.sh

builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
