---
# Build and run the Go binary from the repo
# REQUIRES: Go v1.16+ installed
- id: pike-docs-go
  name: pike-docs
  description: Generate Policy documentation for Terraform modules (via Go binary)
  language: golang
  entry: pike
  pass_filenames: false
  types: [ terraform ]

# Build and run `pike-docs` assuming it was installed manually
# or via package manager
# REQUIRES: pike-docs to be installed and on the $PATH
- id: pike-docs-system
  name: pike-docs
  description: Generate Policy documentation for Terraform modules (via locally-installed CLI)
  language: system
  entry: pike
  pass_filenames: false
  types: [ terraform ]

# Builds and runs the Docker image from the repo
# REQUIRES: Docker installed
- id: pike-docs-docker
  name: pike-docs
  description: Generate Policy documentation for Terraform modules (via Docker build)
  language: docker
  entry: pike
  pass_filenames: false
  types: [ terraform ]
