Main:
  files:
    - $all
    - "!$test"
  allow:
    - $gostd
    - github.com/aws/aws-sdk-go-v2/aws
    - github.com/aws/aws-sdk-go-v2/config
    - github.com/aws/aws-sdk-go-v2/service/iam
    - github.com/awslabs/goformation/v7/cloudformation
    - github.com/awslabs/goformation/v7/cloudformation/tags
    - github.com/go-git/go-git/v5
    - github.com/go-git/go-git/v5/plumbing
    - github.com/gobeam/stringy
    - github.com/hashicorp/hc-install/product
    - github.com/hashicorp/hc-install/releases
    - github.com/hashicorp/terraform-exec/tfexec
    - github.com/jameswoolfenden/pike/src
    - github.com/rs/zerolog
    - github.com/rs/zerolog/log
    - github.com/urfave/cli/v2
    - github.com/yudai/gojsondiff
    - github.com/yudai/gojsondiff/formatter
    - sato/src/arm
    - sato/src/cf
    - sato/src/see
  deny:
Test:
  files:
    - $test
  allow:
    - $gostd
  deny:
pike:
  files:
    - $all
  allow:
    - $gostd
    - github.com/aws/aws-sdk-go-v2/aws
    - github.com/aws/aws-sdk-go-v2/config
    - github.com/aws/aws-sdk-go-v2/service/iam
    - github.com/awslabs/goformation/v7/cloudformation
    - github.com/awslabs/goformation/v7/cloudformation/tags
    - github.com/go-git/go-git/v5
    - github.com/go-git/go-git/v5/plumbing
    - github.com/gobeam/stringy
    - github.com/hashicorp/hc-install/product
    - github.com/hashicorp/hc-install/releases
    - github.com/hashicorp/terraform-exec/tfexec
    - github.com/jameswoolfenden/pike/src
    - github.com/rs/zerolog
    - github.com/rs/zerolog/log
    - github.com/urfave/cli/v2
    - github.com/yudai/gojsondiff
    - github.com/yudai/gojsondiff/formatter
    - sato/src/arm
    - sato/src/cf
    - sato/src/see
