package pike

import (
	"bytes"
	_ "embed" // required for embed
	"encoding/json"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"github.com/JamesWoolfenden/arn"
	"github.com/rs/zerolog/log"
)

//go:embed terraform.policy.template
var policyTemplate []byte

//go:embed aws_iam_role.tf
var roleTemplate []byte

type policyDetails struct {
	Policy      string
	Name        string
	Path        string
	Description string
}

// NewAWSPolicy constructor.
func NewAWSPolicy(actions []string, resources bool) (Policy, error) {
	if len(actions) == 0 {
		return Policy{}, &emptyActionsError{}
	}

	something := Policy{Version: "2012-10-17"}

	sort.Strings(actions)

	categories := make([]string, len(actions))

	for index, action := range actions {
		categories[index] = strings.Split(action, ":")[0]
	}

	myArn := new(arn.AwsArn)

	if resources {
		_, _ = myArn.Builder()
	}

	sections := Unique(categories)

	var statements []Statement

	for count, section := range sections {
		var myActions []string

		myResource := []string{"*"}

		resource := "*"

		for _, action := range actions {
			mySection := section + ":"
			if strings.Contains(action, mySection) {
				myActions = append(myActions, action)
			}
		}

		if myActions == nil {
			return something, &emptyActionsError{}
		}

		// todo expand with new plan function
		if resources {
			myArn.Service = section
			myArn.Resource = &resource
			myResource, _ = myArn.Builder()
		}

		state := NewStatement(
			"VisualEditor"+strconv.Itoa(count),
			allow,
			myActions,
			myResource)

		statements = append(statements, state)
	}

	something.Statements = statements

	return something, nil
}

// GetPolicy creates new iam polices from a list of Permissions.
func GetPolicy(actions Sorted, resources bool, policyName string) (OutputPolicy, error) {
	var (
		OutPolicy OutputPolicy
		empty     = true
		err       error
	)

	if actions.AWS != nil {
		empty = false
		OutPolicy.AWS, err = AWSPolicy(Unique(actions.AWS), resources, policyName)
		if err != nil {
			log.Error().Err(err).Msg("AWS policy generation failed")
		}
	}

	if actions.GCP != nil {
		empty = false
		OutPolicy.GCP, err = GCPPolicy(Unique(actions.GCP), policyName)
		if err != nil {
			log.Error().Err(err).Msg("GCP policy generation failed")
		}
	}

	if actions.AZURE != nil {
		empty = false
		OutPolicy.AZURE, err = AZUREPolicy(Unique(actions.AZURE), policyName)
		if err != nil {
			log.Error().Err(err).Msg("Azure policy generation failed")
		}
	}

	if empty {
		return OutPolicy, &emptyPermissionsError{}
	}

	return OutPolicy, nil
}

// AWSPolicy create an IAM policy.
func AWSPolicy(permissions []string, resources bool, policyName string) (AwsOutput, error) {
	var OutPolicy AwsOutput

	Policy, err := NewAWSPolicy(permissions, resources)
	if err != nil {
		return OutPolicy, &newAWSPolicyError{err}
	}

	indent, err := json.MarshalIndent(Policy, "", "    ")
	if err != nil {
		log.Error().Err(err).Msg("failed to marshal AWS policy")

		return OutPolicy, &marshallAWSPolicyError{err}
	}

	var theDetails policyDetails

	if policyName != "" {
		theDetails = policyDetails{string(indent), policyName, "/", "Pike Autogenerated policy from IAC"}
	} else {
		theDetails = policyDetails{string(indent), defaultPolicyName, "/", "Pike Autogenerated policy from IAC"}
	}

	var output bytes.Buffer

	tmpl, err := template.New("test").Parse(string(policyTemplate))
	if err != nil {
		return OutPolicy, &templateParseError{err}
	}

	err = tmpl.Execute(&output, theDetails)
	if err != nil {
		return OutPolicy, &templateExecuteError{err}
	}

	OutPolicy.Terraform = output.String()
	OutPolicy.JSONOut = string(indent) + "\n"

	return OutPolicy, nil
}

// Unique make slice unique.
func Unique(s []string) []string {
	seen := make(map[string]struct{}, len(s))

	var result []string

	for _, str := range s {
		if _, ok := seen[str]; !ok {
			seen[str] = struct{}{}
			result = append(result, str)
		}
	}

	sort.Strings(result)

	return result
}

var minifyReplacer = strings.NewReplacer("\n", "", "\r", "", "\t", "", "	", "", " ", "")

func Minify(JSONOut string) string {
	return minifyReplacer.Replace(JSONOut)
}
