on:
  push:
    branches:
      - master

name: CI
permissions: read-all

jobs:
  test:
    env:
      GITHUB_API: ${{ secrets.PAT }}
      GOTOOLCHAIN: auto
    ## We want to define a strategy for our job
    strategy:
      ## this will contain a matrix of all the combinations
      ## we wish to test again:
      matrix:
        go-version: [ 1.25.8 ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]

    ## Defines the platform for each test run
    runs-on: ${{ matrix.platform }}

    ## the steps that will be run through for each version and platform
    ## combination
    steps:
      ## sets up go based on the version
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go-version }}

      ## checks out our code locally, so we can work with the files
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      ## runs go test ./...
      - name: Build
        env:
          GOTOOLCHAIN: auto
        run: go build ./...

      ## runs go test ./...
      - name: Test
        env:
          GOTOOLCHAIN: auto
        run: go test ./... -coverprofile=./cover.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@3f20e214133d0983f9a10f3d63b0faf9241a3daa # v6.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
